backend:
  name: github
  repo: adeonir-com/adeonir.com
  branch: master
  site_domain: adeonir.netlify.com

publish_mode: editorial_workflow
media_folder: static/uploads
public_folder: /uploads

collections:
  - name: posts
    label: Posts
    folder: posts
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Descrição', name: 'description', widget: 'string' }
      - {
          label: 'Date',
          name: 'date',
          widget: 'datetime',
          format: 'YYY-MM-DD hh:mm:ss',
        }
      - {
          label: 'Category',
          name: 'category',
          widget: 'select',
          options: ['html', 'css', 'js', 'misc', 'music'],
        }
      - { label: 'Feature Image', name: 'image', widget: 'image' }
      - { label: 'Content', name: 'body', widget: 'markdown' }
